### ISSUE TITLE
useStore failed to get the state slice

### ISSUE THREAD

**Issue by LavaCxx** [wobsoriano/solid-zustand#11]
When I use createWithSignal, useStore sometimes returns the entire state object after a period of time, instead of the selected slice.
```ts
const feeds=useStore(state=>state.feeds)
console.log('feeds',feeds())

setTimeout(()=>{
  console.log('feeds',feeds())
},1000)
```
<img width="582" alt="image" src="https://github.com/wobsoriano/solid-zustand/assets/48022591/4167832e-b428-4919-b87f-49af4b8d2d38">

**Comment by durkiewicz** [comment]
The same happened for me. I ended up using the store without any selectors.

**Comment by wobsoriano** [comment]
Stupid me 🤦🏼 fixed
