### ISSUE TITLE
performance improvement maybe?

### ISSUE THREAD

**Issue by bigmistqke** [wobsoriano/solid-zustand#7]
Instead of creating a store and subscribing + reconciling for each `useStore`-call, why not only reconcile the root and have the selectors be derived? 

see [playground](https://playground.solidjs.com/anonymous/189403d3-c60b-42c2-8e7d-049e7b477d28)

con: 
- return-type of selector is an accessor.
- I guess with the previous implementation you could import the zustand-stores as singletons in solid-start? (or do you also need to wrap them in contexts? I am no expert w ssr)

plus:
- 1 single store per create
- can also select primitives instead of only select objects 
- I assume it will be more performant in most of the cases, but did not bench it.

**Comment by bigmistqke** [comment]
Another option: I looked back at `solid-three`, that initially was using zustand/vanilla, to see how they implemented it

see [playground](https://playground.solidjs.com/anonymous/5e07013f-2192-431f-9a89-287c10f4b2fc)

It doesn't use stores at all, but instead subscribes to zustand and sets a signal.
It will be a tiny bit less granular, but you don't have to pay for reconciliation + proxies.

**Comment by wobsoriano** [comment]
@bigmistqke can you take a look at the PR if it makes sense?
