### ISSUE TITLE
Wrong typings - fails in moduleResolution

### ISSUE THREAD

**Issue by ivancuric** [wobsoriano/solid-zustand#9]
The way that the package.json is set up messes up any non `node` module resolutions:

https://arethetypeswrong.github.io/?p=solid-zustand%401.7.0

## Problems
❗️[Incorrect default export](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseExportDefault.md)

The resolved types use export default where the JavaScript file appears to use module.exports =. This will cause TypeScript under the node16 module mode to think an extra .default property access is required, but that will likely fail at runtime. These types should use export = instead of export default.

❌ [No types](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/UntypedResolution.md)

Import resolved to JavaScript files, but no type declarations were found.

|   |   |
|---|---|
| node10 | ❗️ Incorrect default export |
| node16 (from CJS) | ❗️ Incorrect default export |
| node16 (from ESM) | ❌ No types |
| bundler | ❌ No types |

**Comment by CHE1RON** [comment]
Same here, using `solid-zustand` inside a Tauri app ..

**Comment by wobsoriano** [comment]
Should be fixed now

https://arethetypeswrong.github.io/?p=solid-zustand@1.7.1

Feel free to reopen!
